modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/Brian-Wuest/MC-Prefab/issues" #optional

[[mods]] #mandatory
    modId="prefab" #mandatory
    version="1.4.0.15" #mandatory
    displayName="Prefab" #mandatory
    #logoFile="" #optional
    updateJSONURL="https://raw.githubusercontent.com/Brian-Wuest/MC-Prefab/master/changeLog.json" #optional
    displayURL="https://www.curseforge.com/minecraft/mc-mods/prefab" #optional
    credits="Kaojinn" #optional
    authors="WuestMan" #optional
    description='''
Provides ways of making pre-fabricated houses and other structures.
Thanks to Kaojinn for making the textures and the construction of the ideas.
Structure Preview functionality adapted from Botania by Vazkii http://botaniamod.net/license.php.
'''
[[dependencies.prefab]]
    modId="forge" #mandatory
    mandatory=false #mandatory
    versionRange="[28.2.3,)" #mandatory
    ordering="NONE"
    side="BOTH"